apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .dockerconfigjson: bWlraGFpbG92MjY6Z2hwX3ROQlJ1MGhidFV0cXV4bXk4UTF5cXBzS21Rd1h6aDFzMElvQQ==
type: kubernetes.io/dockerconfigjson