server.port=8000

cinemaabyss.monolith-url=http://monolith:8080
cinemaabyss.movies-service-url=http://movies-service:8081
cinemaabyss.events-service-url=http://events-service:8082


cinemaabyss.gradual-migration=true
cinemaabyss.movies-migration-percent=50


logging.level.com.cinemaabyss.proxy=INFO
logging.level.com.cinemaabyss.proxy.service=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

rest-template.timeout=5000