apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
  labels:
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJiV2xyYUdGcGJHOTJNalk2WjJod1h6SkhlRkZrU0V0RmRITmlaakJrWTFoc2NsQnlTVGQ1TURGclFsRldNakJ5Vm5sQmNRPT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson